Traceback (most recent call last):
  File "/home/jnapolitano/Projects/USSupremeCourtMetaDataGraph/active_code_base/loc_scraper_3.py", line 521, in <module>
    main()
  File "/home/jnapolitano/Projects/USSupremeCourtMetaDataGraph/active_code_base/loc_scraper_3.py", line 499, in main
    for obj in search_result_generator():   
  File "/home/jnapolitano/Projects/USSupremeCourtMetaDataGraph/active_code_base/loc_scraper_3.py", line 455, in search_result_generator
    time.sleep(61)
KeyboardInterrupt
Traceback (most recent call last):
  File "/home/jnapolitano/Projects/USSupremeCourtMetaDataGraph/active_code_base/loc_scraper_3.py", line 521, in <module>
    main()
  File "/home/jnapolitano/Projects/USSupremeCourtMetaDataGraph/active_code_base/loc_scraper_3.py", line 501, in main
    with cd("output_2"):
  File "/home/jnapolitano/Projects/USSupremeCourtMetaDataGraph/active_code_base/loc_scraper_3.py", line 44, in __enter__
    os.chdir(self.newPath)
FileNotFoundError: [Errno 2] No such file or directory: 'output_2'
